server:
  port: 10086 #端口
spring:
  application:
    name: demo-eureka #应用名
  freemarker:
    prefer-file-system-access: false #是否优先从文件系统加载template，默认为true。不添加此配置访问不了eureka主页
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl: # EurekaServer的地址，现在是⾃己的地址，如果是集群，需要加上其它Server 的地址。
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: false # 是否注册⾃己的信息到EurekaServer，默认是true
    fetch-registry: false # 是否拉取其它服务的信息，默认是true
    registry-fetch-interval-seconds: 5 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    instance-info-replication-interval-seconds: 5 #客户端实例信息变化上报到eureka服务的时间周期，值越小上报越频繁，eureka服务器应用状态管理一致性越高
  instance:
    prefer-ip-address: true # 当调⽤用getHostname获取实例例的hostname时，返回ip⽽而不不是 host名称
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5 #eureka client发送心跳给server端的频率
    lease-expiration-duration-in-seconds: 15 #默认90秒，eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
  server:
    enable-self-preservation: false #是否开启自我保护模式，默认为true。
    eviction-interval-timer-in-ms: 5000 #eureka server清理无效节点的时间间隔，默认60秒
    use-read-only-response-cache: false #应用实例下线时有告知 Eureka Server 下线，但是由于 Eureka Server 的 REST API 有 response cache，因此需要等待缓存过期才能更新，关闭缓存可以缩短此部分等待时间


