server:
  port: 10010 #端口
spring:
  application:
    name: demo-core #应用名

  #redis配置，需要放到spring下面
  redis:
    redisson: #配置redisson配置文件名称，如果名字为redisson.yaml可以不配置
      file: classpath:redisson.yaml
    database: 0
    #password: pbmp_redis
    jedis: #连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: -1 #最大等待时间
        max-idle: 8 #最大空闲连接数
        min-idle: 0 #最小空闲连接数
    # ----sentinel 哨兵----
    sentinel:
      master: mymaster
      nodes: 10.10.57.42:26379,10.10.57.41:26479,10.10.57.42:26380
#eureka配置
eureka:
  client:
    healthcheck:
      enabled: true #健康检测方式，需要添加spring-boot-starter-actuator
    serviceUrl:
      #eureka服务端的地址，如果多个用","隔开
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: true # 是否注册⾃己的信息到EurekaServer，默认是true
    fetch-registry: true # 是否拉取其它服务的信息，默认是true
    registry-fetch-interval-seconds: 5 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    instance-info-replication-interval-seconds: 5 #客户端实例信息变化上报到eureka服务的时间周期，值越小上报越频繁，eureka服务器应用状态管理一致性越高
  instance:
    prefer-ip-address: true # 当调⽤用getHostname获取实例例的hostname时，返回ip⽽而不不是 host名称
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5 #eureka client发送心跳给server端的频率
    lease-expiration-duration-in-seconds: 15 #默认90秒，eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。




#核心服务
demo-core:
  ribbon:
    #Ribbon分发请求策略，使用自定义的灰度策略，默认是轮询
#    NFLoadBalancerRuleClassName: com.example.core1.rule.GrayscaleRibbonRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #建立链接超时时间
    ConnectTimeout: 5000
    #读超时时间
    ReadTimeout: 20000
    MaxTotalConnections: 200
    MaxConnectionsPerHost: 100

#curator相关配置信息
curator:
  retryCount: 5  #重试次数
  elapsedTimeMs: 5000   #重试间隔时间
  connectString: 10.10.178.206:2181   # zookeeper 地址
  sessionTimeoutMs: 60000  # session超时时间
  connectionTimeoutMs: 5000  # 连接超时时间
  seqPrantName: /seqPrantNode # 生成流水根节点名称
  seqName: /seqNode- # 生成流水节点名称，/seqNode-20200928 每天从0开始生成